# Generated by Django 2.2 on 2019-04-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ateliers',
            name='places',
            field=models.BooleanField(default=True),
        ),
    ]
