# Generated by Django 2.2 on 2019-04-22 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0002_auto_20190421_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='nom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
