# Generated by Django 2.2 on 2019-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0003_auto_20190422_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
