# Generated by Django 2.2 on 2019-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0004_auto_20190422_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='membres',
            name='nom',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='membres',
            name='prenom',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
