# Generated by Django 2.2 on 2019-04-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0006_ateliers_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ateliers',
            name='participant',
        ),
    ]
