# Generated by Django 2.2 on 2019-04-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0008_auto_20190422_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='ateliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga_website.Ateliers'),
        ),
        migrations.AlterField(
            model_name='membres',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='membres',
            name='nom',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='membres',
            name='prenom',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
