# Generated by Django 2.2 on 2019-04-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0009_auto_20190422_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membres',
        ),
    ]
