# Generated by Django 2.2 on 2019-04-25 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yoga_website', '0011_ateliers_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ateliers',
            name='participants',
        ),
        migrations.AddField(
            model_name='ateliers',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
