# Generated by Django 2.2 on 2019-10-27 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yoga_website', '0013_auto_20190425_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=ChildProcessError, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
