# Generated by Django 2.2 on 2019-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0016_auto_20191030_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atelier', models.OneToOneField(on_delete=ChildProcessError, to='yoga_website.Atelier')),
                ('client', models.OneToOneField(on_delete=ChildProcessError, to='yoga_website.Client')),
            ],
        ),
    ]
