# Generated by Django 2.2 on 2019-11-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0017_inscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atelier',
            name='participants',
        ),
    ]
