# Generated by Django 2.2 on 2019-11-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0018_remove_atelier_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscribe',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga_website.Client'),
        ),
    ]
