# Generated by Django 2.2 on 2019-11-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0021_auto_20191107_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscribe',
            name='atelier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga_website.Atelier'),
        ),
    ]
