# Generated by Django 2.2.7 on 2019-11-26 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('nb_places', models.IntegerField()),
                ('places', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('lieux', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(default='test', max_length=254)),
                ('nom', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('activate', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=255)),
                ('test', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=ChildProcessError, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga_website.Atelier')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga_website.Client')),
            ],
        ),
    ]
