# Generated by Django 2.2.7 on 2019-11-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='activate',
        ),
        migrations.RemoveField(
            model_name='client',
            name='test',
        ),
    ]
